name: 'YC COI Container Deploy'
description: 'GitHub Action to deploy container to Yandex Cloud COI VM'
author: 'Nikolay Matrosov'
inputs:
  yc-sa-json-credentials:
    required: false
    description: 'JSON containing authorized key for Service Account.
      Either this or `yc-iam-token` or `yc-sa-id` should be provided.
      More info https://cloud.yandex.ru/docs/container-registry/operations/authentication#sa-json'
  yc-iam-token:
    required: false
    description: 'IAM token for Yandex Cloud. 
      Either this or `yc-sa-json-credentials` or `yc-sa-id` should be provided.
      More info https://yandex.cloud/ru/docs/iam/concepts/authorization/iam-token'
  yc-sa-id:
    required: false
    description: 'Service Account ID. Will be uses to exchange GitHub token to Yandex Cloud token.
      Either this or `yc-iam-token` or `yc-sa-json-credentials` should be provided.
      More info https://yandex.cloud/ru/docs/iam/concepts/workload-identity'
  folder-id:
    required: true
    description: 'Folder ID'
  vm-name:
    required: true
    description: 'VM name to find or create in the provided folder.'
  vm-service-account-id:
    required: false
    description: 'Id of service account that will be attached to VM.'
  vm-service-account-name:
    required: false
    description: 'Name of service account that will be attached to VM. Will be used to find out the ID of SA.'
  vm-cores:
    required: false
    description: 'Number of Cores'
    default: '2'
  vm-memory:
    required: false
    description: 'Memory. Format: `\\d(Mb|Gb)`. E.g. 1Gb'
    default: '1GB'
  vm-core-fraction:
    required: false
    description: 'Core fraction'
    default: '100'
  vm-disk-type:
    required: false
    description: 'Disk type. Values: network-ssd, network-hdd, etc. More info https://cloud.yandex.com/en-ru/docs/managed-clickhouse/concepts/storage'
    default: 'network-ssd'
  vm-disk-size:
    required: false
    description: 'Disk size. Format: `\\d(Mb|Gb)`. E.g. 30Gb'
    default: '30GB'
  vm-zone-id:
    required: false
    description: 'Zone ID'
    default: 'ru-central1-a'
  vm-subnet-id:
    required: true
    description: 'The subnet ID where the VM will be created'
  vm-public-ip:
    required: false
    description: 'Public IP address'
  vm-platform-id:
    required: false
    description: 'Compute platform Id'
    default: 'standard-v3'
  user-data-path:
    required: true
    description: 'Path to the `user-data.yaml` file inside repo.'
  docker-compose-path:
    required: true
    description: 'Path to the `docker-compose.yaml` file inside repo.'
outputs:
  instance-id:
    description: 'Instance ID'
  disk-id:
    description: 'Boot disk ID that was created for the instance'
  public-ip:
    description: 'Public IP address that was assigned to the instance'
  created:
    description: 'A flag that indicates whether instance was created or updated'
branding:
  color: blue
  icon: upload-cloud
runs:
  using: 'node20'
  main: 'dist/index.js'
